### ISSUE TITLE
Github url in npm is wrong

### ISSUE THREAD

**Issue by xnacly** [rsnakdmx/vite-plugin-purgecss-v5#1]
Is `https://github.com/rsnakdmx/vite-plugin-purgecss-updated-v5`, should be `https://github.com/rsnakdmx/vite-plugin-purgecss-v5` at https://www.npmjs.com/package/vite-plugin-purgecss-updated-v5

**Comment by rsnakdmx** [comment]
Thanks, i correct that URL in the new version 1.2.3.
